# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]  

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run prod
    - run: npm test  
      env:
        CI: true

  package:
    needs: [build]
    strategy:
      matrix:
        os: [windows-latest, macos-latest]  

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run prod
    - name: Build Windows installer
      if: matrix.os == 'windows-latest'
      run: npm run build:win  
      env:
        CI: true 
    - name: Build macOS installer
      if: matrix.os == 'macos-latest'
      run: npm run build:mac
      env:
        CI: true
  
      
